### ISSUE TITLE
Schalter und Fernbedinung

### ISSUE THREAD

**Issue by Arakansas** [kdietrich/homebridge-devolo#28]
hallo, leider werden meine DEVOLO Schalter und Fernbedienungen nicht erkannt. 
Ist da was geplant und wann kann man mit einet Umsetzung rechnen?

Sonst ein hammer tool!!

**Comment by kdietrich** [comment]
Falls du mit dem Devolo Schalter den Wandschalter meinst, ist dieser unterstützt. Die Fernbedienung fehlt tatsächlich noch, wird aber sobald ich eine in den Händen halte, hinzugefügt.

**Comment by Arakansas** [comment]
Hallo, 

der Schalter den man irgendwo hinkleben kann von DEVOLO findet er auch nicht.

Device devolo.model.Unknown:Device is not supported (yet). Open an issue on github and ask for adding it.
Device devolo.model.Wall:Control is not supported (yet). Open an issue on github and ask for adding it.
Device devolo.model.Remote:Control is not supported (yet). Open an issue on github and ask for adding it.
Device devolo.model.Remote:Control is not supported (yet). Open an issue on github and ask for adding it.
Device devolo.model.Wall:Control is not supported (yet). Open an issue on github and ask for adding it.
Device devolo.model.Unknown:Device is not supported (yet). Open an issue on github and ask for adding it.
Device devolo.model.Unknown:Device is not supported (yet). Open an issue on github and ask for adding it.
Device devolo.model.Unknown:Device is not supported (yet). Open an issue on github and ask for adding it.
Device devolo.model.Unknown:Device is not supported (yet). Open an issue on github and ask for adding it.
Device devolo.model.Unknown:Device is not supported (yet). Open an issue on github and ask for adding it.


Gruß
Andreas

**Comment by nicoh88** [comment]
@Arakansas

Doch der Schalter funktioniert.
Hast du eventuell nicht die aktuelle Version installiert?

Prüfe mit:
`npm -g outdated --long`

Gegebenenfalls: 
`npm update -g homebridge-devolo --unsafe-perm`

Gruß Nico

**Comment by Arakansas** [comment]
Du hast recht war nicht die aktuelle.

Danke -  nun findet er die Schalter

Gruß
Andreas

**Comment by kdietrich** [comment]
@Arakansas In der noch nicht veröffentlichten Version `v0.1.7-dev` wird nun auch die Devolo Fernbedienung unterstützt. Du kannst diese vorab mit `npm install -g kdietrich/homebridge-devolo --unsafe-perm` installieren und testen.

**Comment by Arakansas** [comment]
Hallo, 

das hat ja super geklappt. DANKE

wenn Du jetzt noch die Sirene und die Relais zum laufen bringst bin ich überglücklich.

Aeotec Sirene ZW080-BI - Z-Wave Plus <https://www.amazon.de/Aeotec-Sirene-ZW080-BI-Z-Wave-Plus/dp/B00P00N2H8/ref=sr_1_1?ie=UTF8&qid=1519737793&sr=8-1&keywords=zwave+sirene>

Fibaro Relais Unterputzeinsatz 1 Schalter 2,5kW - Z-Wave, 1 Stück, FIBEFGS-213 <https://www.amazon.de/Fibaro-Relais-Unterputzeinsatz-Schalter-5kW/dp/B01KHWI0HK/ref=sr_1_3?ie=UTF8&qid=1519737829&sr=8-3&keywords=zwave+relais>


DANKE

Gruß
Andreas

**Comment by nicoh88** [comment]
Hallo @Arakansas,

könntest du bitte auf die neueste Dev-Version updaten?
`npm install -g kdietrich/homebridge-devolo --unsafe-perm`

Und die [hier](https://github.com/kdietrich/homebridge-devolo#support-of-new-devices) beschrieben Schritte durchführen. (vorher den normalen Homebridge-Prozess beenden/stoppen)
`homebridge -D | tee debugoutput.log`

Die damit erstellte Datei kannst du anschließend in einem **neuen** Issue hochladen. Diese dient @kdietrich als Vorlage für die Geräteintegration. 

Gruß Nico

**Comment by Arakansas** [comment]
Hi Nico,

ganz ehrlich ich verstehe nur Bahnhof!

so wie ich das verstanden und durchgeführt habe, bekam ich folgenden Output


root@pi:/home/pi# homebridge -D | tee debugoutput.log
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[2/27/2018, 6:11:56 PM] Loaded plugin: homebridge-devolo
[2/27/2018, 6:11:56 PM] Registering platform 'homebridge-devolo.Devolo'
[2/27/2018, 6:11:56 PM] ---
[2/27/2018, 6:11:56 PM] Loaded config.json with 0 accessories and 1 platforms.
[2/27/2018, 6:11:56 PM] ---
[2/27/2018, 6:11:56 PM] Loading 1 platforms...
[2/27/2018, 6:11:56 PM] [Devolo] Initializing Devolo platform...
[2/27/2018, 6:11:56 PM] [Devolo] HBDevoloPlatform > Initializing (Version: 201702221607)
[2/27/2018, 6:11:56 PM] [Devolo] HBDevoloPlatform > Configuration:
{ platform: 'Devolo',
  name: 'Devolo',
  host: '192.168.178.44',
  email: 'xxx',
  password: 'xxx',
  uuid: 'xxx',
  gateway: 'xxx',
  passkey: 'xxx',
  heartrate: 3 }
[2/27/2018, 6:11:56 PM] [Devolo] HBDevoloPlatform > Searching for Devolo Central Unit.
[2/27/2018, 6:11:56 PM] Loading 0 accessories...
Trying to connect to socket.
Websocket open
[2/27/2018, 6:11:56 PM] [Devolo] HBDevoloPlatform > Devolo API Version: 201707161504
[2/27/2018, 6:11:56 PM] [Devolo] HBDevoloCentralUnit > Initializing
[2/27/2018, 6:11:56 PM] [Devolo] HBDevoloPlatform > Central Unit found.
[2/27/2018, 6:11:56 PM] [Devolo] HBDevoloPlatform > SessionID: ID501DB7OklL1NCkjN35CgoO51NcaD0OEhdNL4EEnd
Device devolo.model.Unknown:Device is not supported (yet). Open an issue on github and ask for adding it.
Device devolo.model.Unknown:Device is not supported (yet). Open an issue on github and ask for adding it.
Device devolo.model.Unknown:Device is not supported (yet). Open an issue on github and ask for adding it.
Device devolo.model.Unknown:Device is not supported (yet). Open an issue on github and ask for adding it.
Device devolo.model.Unknown:Device is not supported (yet). Open an issue on github and ask for adding it.
Device devolo.model.Unknown:Device is not supported (yet). Open an issue on github and ask for adding it.
[2/27/2018, 6:11:59 PM] [Devolo] HBDevoloDoorWindowDevice > Initializing
[2/27/2018, 6:11:59 PM] [Devolo] HBDevoloSmokeDetectorDevice > Initializing
[2/27/2018, 6:11:59 PM] [Devolo] HBDevoloWallSwitchDevice > Initializing
[2/27/2018, 6:11:59 PM] [Devolo] HBDevoloSwitchMeterDevice > Initializing
[2/27/2018, 6:11:59 PM] [Devolo] HBDevoloDoorWindowDevice > Initializing
[2/27/2018, 6:11:59 PM] [Devolo] HBDevoloRemoteControlDevice > Initializing
[2/27/2018, 6:11:59 PM] [Devolo] HBDevoloRemoteControlDevice > Initializing
[2/27/2018, 6:11:59 PM] [Devolo] HBDevoloMotionDevice > Initializing
[2/27/2018, 6:11:59 PM] [Devolo] HBDevoloMotionDevice > Initializing
[2/27/2018, 6:11:59 PM] [Devolo] HBDevoloSmokeDetectorDevice > Initializing
[2/27/2018, 6:11:59 PM] [Devolo] HBDevoloWallSwitchDevice > Initializing
[2/27/2018, 6:11:59 PM] [Devolo] HBDevoloSwitchMeterDevice > Initializing
[2/27/2018, 6:11:59 PM] [Devolo] HBDevoloSmokeDetectorDevice > Initializing
[2/27/2018, 6:11:59 PM] [Devolo] HBDevoloMotionDevice > Initializing
[2/27/2018, 6:12:00 PM] [Devolo] Initializing platform accessory 'Devolo Central Unit'...
[2/27/2018, 6:12:00 PM] [Devolo] Initializing platform accessory 'Terrassentür'...
[2/27/2018, 6:12:00 PM] [Devolo] Initializing platform accessory 'Rauchmelder'...
[2/27/2018, 6:12:00 PM] [Devolo] Initializing platform accessory 'Schalter Brunnen '...
[2/27/2018, 6:12:00 PM] [Devolo] Initializing platform accessory 'Steckdose 1'...
[2/27/2018, 6:12:00 PM] [Devolo] Initializing platform accessory 'Kellerfenster'...
[2/27/2018, 6:12:00 PM] [Devolo] Initializing platform accessory 'Fernbedienung 1'...
[2/27/2018, 6:12:00 PM] [Devolo] Initializing platform accessory 'Fernbedienung 2'...
[2/27/2018, 6:12:00 PM] [Devolo] Initializing platform accessory 'BM 1'...
[2/27/2018, 6:12:00 PM] [Devolo] Initializing platform accessory 'BM 2 '...
[2/27/2018, 6:12:00 PM] [Devolo] Initializing platform accessory 'Rauchmelder '...
[2/27/2018, 6:12:00 PM] [Devolo] Initializing platform accessory 'Schalter 1'...
[2/27/2018, 6:12:00 PM] [Devolo] Initializing platform accessory 'Steckdose 2'...
[2/27/2018, 6:12:00 PM] [Devolo] Initializing platform accessory 'Rauchmelder '...
[2/27/2018, 6:12:00 PM] [Devolo] Initializing platform accessory 'BM 3'...
Setup Payload:
X-HM://0023OA6328K83
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:





Ist das das was du  brauchst ????



Gruß
Andreas

**Comment by nicoh88** [comment]
Hi Andreas,

ja, fast Perfekt, nur noch eine Kleinigkeit.
Es fehlt nur noch die "_deviceDebugging_" Zeile in deiner "_config.json_".

`"deviceDebugging": false`

Beispiel meiner "_config.json_":

```
{
        "platform": "Devolo",
        "name": "Devolo",
        "host": "192.168.XXX.XX",
        "email": "xxx@xxx.com",
        "password": "xxx",
        "heartrate": 3,
        "uuid": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
        "gateway": "XXXXXXXXXXXXX",
        "passkey": "XXXXXXXXXXXXX XXXXXXXXXXXXX",
        "ruleWhitelist": ["Alarmanlage"],
        "sceneWhitelist": ["Alarmanlage aktivieren", "Alarmanlage deaktivieren"],
        "deviceBlacklist": ["W Sternlampe", "W Herrnhuter Sterne", "W Winterwald", "W Tannenbaum"],
	"deviceDebugging": false
    },
```

Es wird dann eine Datei "_debugoutput.log_" in dem Verzeichnis, in dem du dich per SSH befindest, erzeugt - vermutlich "_/root_". Diese Datei lädst du dann hier hoch - bitte mache aber ein **Issue** auf.

Gruß Nico

**Comment by Arakansas** [comment]
Hi Nico,

meine Config sieht jetzt so aus.

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "123-45-678"
    },

    "platforms": [
        {
           "platform": "Devolo",
           "name": "Devolo",
           "host": "192.168.178.44",
           "email": "andreasgreiter@web.de",
           "password": "Dennis-1909",
           "uuid": "1B314DA8-DFA7-4850-80D6-ACBA6A990DF6",
           "gateway": "1407017270001576",
           "passkey": "9782a6a6895325fb845dd6412ba5711c"
           "deviceDebugging": false
        }
     ],

    "accessories": []
}



Und ich bekomme folgendes Resultat



root@pi:/home/pi# homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[3/3/2018, 2:07:06 PM] Loaded plugin: homebridge-devolo
[3/3/2018, 2:07:06 PM] Registering platform 'homebridge-devolo.Devolo'
[3/3/2018, 2:07:06 PM] ---
[3/3/2018, 2:07:06 PM] There was a problem reading your config.json file.
[3/3/2018, 2:07:06 PM] Please try pasting your config.json file here to validate it: http://jsonlint.com
[3/3/2018, 2:07:06 PM] 
/usr/lib/node_modules/homebridge/lib/server.js:207
    throw err;
    ^

SyntaxError: Unexpected string in JSON at position 528
    at Object.parse (native)
    at Server._loadConfig (/usr/lib/node_modules/homebridge/lib/server.js:201:19)
    at new Server (/usr/lib/node_modules/homebridge/lib/server.js:57:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
root@pi:/home/pi# 



Gruß
Andreas

**Comment by Arakansas** [comment]
Nochmal Hi,

habe das fehlende „ , „  gefunden und nun geht es

Lösch mal meine Daten war ein wenig unvorsichtig



Gruß
Andreas
