### ISSUE TITLE
node v10.14.1 / v11.3.0 - accessoryList - cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by DevoloKit** [kdietrich/homebridge-devolo#48]
Hallo,

ich habe auf einem Mac Mini (Mojave 10.14.1) node v11.3.0 und npm 6.4.1 installiert.
Die config.json ist korrekt, ich bekomme das Devolo-plugin für Homebridge nicht geladen. Woran könnte das liegen?

Mac-mini-Media:~ macmini$ homebridge -D
[3.12.2018, 22:27:28] Loaded config.json with 0 accessories and 1 platforms.
[3.12.2018, 22:27:28] ---
[3.12.2018, 22:27:28] Loaded plugin: homebridge-devolo
[3.12.2018, 22:27:28] Registering platform 'homebridge-devolo.Devolo'
[3.12.2018, 22:27:28] ---
[3.12.2018, 22:27:28] Loading 1 platforms...
[3.12.2018, 22:27:28] [Devolo] Initializing Devolo platform...
[3.12.2018, 22:27:28] [Devolo] HBDevoloPlatform > Initializing (Version: 201702221607)
[3.12.2018, 22:27:28] [Devolo] HBDevoloPlatform > Configuration:
{ platform: 'Devolo',
  name: 'Devolo',
  host: '192.168.178.40',
  email: 'xxx',
  password: 'xxx',
  uuid: 'xxx',
  gateway: 'xxx',
  passkey: 'xxx',
  heartrate: 3 }
[3.12.2018, 22:27:28] [Devolo] HBDevoloPlatform > Searching for Devolo Central Unit.
[3.12.2018, 22:27:28] [Devolo] HBDevoloPlatform > Could not get dhlp portal. Try again later.
Trying to connect to socket.
[3.12.2018, 22:27:28] [Devolo] HBDevoloPlatform > Could not get session. Try again later.
Websocket open
[3.12.2018, 22:27:28] [Devolo] HBDevoloPlatform > Devolo API Version: 201707161504
[3.12.2018, 22:27:28] [Devolo] HBDevoloCentralUnit > Initializing
[3.12.2018, 22:27:28] [Devolo] HBDevoloPlatform > Central Unit found.
[3.12.2018, 22:27:28] [Devolo] HBDevoloPlatform > SessionID: ID11060DB4GopML1GehOMNIlcI9PPapNPOKknOPMLEnd
/usr/local/lib/node_modules/homebridge-devolo/dist/index.js:65
                    throw err;
                    ^

TypeError: Cannot read property 'length' of undefined
    at /usr/local/lib/node_modules/homebridge-devolo/node_modules/node-devolo/dist/Devolo.js:141:39
    at /usr/local/lib/node_modules/homebridge-devolo/node_modules/node-devolo/dist/DevoloApi.js:188:17
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-devolo/node_modules/node-devolo/dist/DevoloApi.js:69:21)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1098:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)

**Comment by nicoh88** [comment]
Hi @DevoloKit,

ich denke, dass `uuid`, `gateway` oder `passkey` falsch ist.
Hast du `homebridge-devolo` ohne diese Parameter einmal sauber gestartet, damit er dir diese anzeigt / generiert? Oder hast du die von irgendwo kopiert?

Gruß Nico

**Comment by DevoloKit** [comment]
Hi Nico,

nein, das ist korrekt gewesen. Ich habe nochmal Homebridge sauber gestartet, dann wurden uuid, gateway und passkey neu übertragen. Wieder in der config.json eingefügt, gleicher Fehler.

Hier meine config.json und danach mein Debug-Log. Wo ist der Fehler, könnte bei Accessoires ein Fehler sein? In Zeile 65 der Index.js wird der Fehler erzeugt:
            var accessoryList = [];
            accessoryList.push(self.centralUnit);
            self.centralUnit.accessories(function (err, accessories) {
                if (err) {
                    throw err;

**config.json:**
{ 
    "bridge": {
                      "name": "Homebridge",
                      "username": "CC:22:3D:E3:CE:31",
                      "port": 51826,
                      "pin": "031-45-154"
                    },

"platforms": [
    {
      "platform": "Devolo",
      "name": "Devolo",
      "host": "192.168.178.40",
      "email": "XXX",
      "password": "XXX",
      "uuid": "XXX",
      "gateway": "XXX",
      "passkey": "XXX",

    }
  ],

"accessories": []

}

## Debug Log ##

Last login: Tue Dec  4 19:23:25 on ttys000
Mac-mini-Media:~ macmini$ homebridge -D
[4.12.2018, 19:25:29] Loaded config.json with 0 accessories and 1 platforms.
[4.12.2018, 19:25:29] ---
[4.12.2018, 19:25:29] Loaded plugin: homebridge-devolo
[4.12.2018, 19:25:29] Registering platform 'homebridge-devolo.Devolo'
[4.12.2018, 19:25:29] ---
[4.12.2018, 19:25:29] Loading 1 platforms...
[4.12.2018, 19:25:29] [Devolo] Initializing Devolo platform...
[4.12.2018, 19:25:29] [Devolo] HBDevoloPlatform > Initializing (Version: 201702221607)
[4.12.2018, 19:25:29] [Devolo] HBDevoloPlatform > Configuration:
{ platform: 'Devolo',
  name: 'Devolo',
  host: '192.168.178.40',
  email: 'xxx',
  password: 'xxx',
  heartrate: 3 }
[4.12.2018, 19:25:29] [Devolo] HBDevoloPlatform > Searching for Devolo Central Unit.
[4.12.2018, 19:25:29] Loading 0 accessories...
[4.12.2018, 19:25:29] [Devolo] HBDevoloPlatform > Authorization failed. Check email and password.
[4.12.2018, 19:25:29] [Devolo] HBDevoloPlatform > Could not fetch gateway. Try again later.
[4.12.2018, 19:25:30] [Devolo] HBDevoloPlatform > Could not fetch passkey. Try again later.
[4.12.2018, 19:25:30] [Devolo] HBDevoloPlatform > Could not get dhlp portal. Try again later.
Trying to connect to socket.
[4.12.2018, 19:25:30] [Devolo] HBDevoloPlatform > Could not get session. Try again later.
Websocket open
[4.12.2018, 19:25:30] [Devolo] HBDevoloPlatform > Devolo API Version: 201707161504
[4.12.2018, 19:25:30] [Devolo] HBDevoloCentralUnit > Initializing
[4.12.2018, 19:25:30] [Devolo] HBDevoloPlatform > Central Unit found.
[4.12.2018, 19:25:30] [Devolo] HBDevoloPlatform > Please edit config.json and restart homebridge.
  "platforms": [
    {
      "platform": "Devolo",
      "name": "Devolo",
      "host": "192.168.178.40",
      "email": "X",
      "password": "X",
      "uuid": "X",
      "gateway": "X“,
      "passkey": "X"
    }
  ]



Mac-mini-Media:~ macmini$ homebridge -D
[4.12.2018, 19:26:32] Loaded config.json with 0 accessories and 1 platforms.
[4.12.2018, 19:26:32] ---
[4.12.2018, 19:26:32] Loaded plugin: homebridge-devolo
[4.12.2018, 19:26:32] Registering platform 'homebridge-devolo.Devolo'
[4.12.2018, 19:26:32] ---
[4.12.2018, 19:26:32] Loading 1 platforms...
[4.12.2018, 19:26:32] [Devolo] Initializing Devolo platform...
[4.12.2018, 19:26:32] [Devolo] HBDevoloPlatform > Initializing (Version: 201702221607)
[4.12.2018, 19:26:32] [Devolo] HBDevoloPlatform > Configuration:
{ platform: 'Devolo',
  name: 'Devolo',
  host: '192.168.178.40',
  email: 'xxx',
  password: 'xxx',
  uuid: 'xxx',
  gateway: 'xxx',
  passkey: 'xxx',
  heartrate: 3 }
[4.12.2018, 19:26:32] [Devolo] HBDevoloPlatform > Searching for Devolo Central Unit.
[4.12.2018, 19:26:32] Loading 0 accessories...
[4.12.2018, 19:26:32] [Devolo] HBDevoloPlatform > Could not get dhlp portal. Try again later.
Trying to connect to socket.
[4.12.2018, 19:26:32] [Devolo] HBDevoloPlatform > Could not get session. Try again later.
Websocket open
[4.12.2018, 19:26:33] [Devolo] HBDevoloPlatform > Devolo API Version: 201707161504
[4.12.2018, 19:26:33] [Devolo] HBDevoloCentralUnit > Initializing
[4.12.2018, 19:26:33] [Devolo] HBDevoloPlatform > Central Unit found.
[4.12.2018, 19:26:33] [Devolo] HBDevoloPlatform > SessionID: ID11104DBPAbcG32BnnB77PboE5PIceP13KnjE19EEnd
/usr/local/lib/node_modules/homebridge-devolo/dist/index.js:65
                    throw err;
                    ^

TypeError: Cannot read property 'length' of undefined
    at /usr/local/lib/node_modules/homebridge-devolo/node_modules/node-devolo/dist/Devolo.js:141:39
    at /usr/local/lib/node_modules/homebridge-devolo/node_modules/node-devolo/dist/DevoloApi.js:188:17
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-devolo/node_modules/node-devolo/dist/DevoloApi.js:69:21)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1098:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
Mac-mini-Media:~ macmini$

**Comment by nicoh88** [comment]
Hmm, eigenartig.

Hast du all deinen devolo Geräten einen Ort zugewiesen? Ich habe da noch was in Erinnerung, dass es Probleme gab, wenn Geräte keinem Ort zugeordnet war...

Du hast nur eine Zentrale in deinem myDevolo?

Little Snitch oder ähnliches, was deinen Netzwerkverkehr blockieren könnte, hast du nicht am Laufen?

Viele Grüße

**Comment by DevoloKit** [comment]
Es ist definitiv ein Bug in node (inkl. npm 6.4.1). Mit node v10.14.1 oder node v11.3.0 hat es nicht funktioniert.

Ich habe jetzt node-v8.11.4pkg installiert und mit node v8.11.4 (inkl. npm v5.10.0) läuft es stabil auf Max OS X Mojave.

Mac-mini-Media:.homebridge macmini$ homebridge -D
[2018-12-4 20:41:02] Loaded config.json with 0 accessories and 1 platforms.
[2018-12-4 20:41:02] ---
[2018-12-4 20:41:02] Loaded plugin: homebridge-devolo
[2018-12-4 20:41:02] Registering platform 'homebridge-devolo.Devolo'
[2018-12-4 20:41:02] ---
[2018-12-4 20:41:02] Loading 1 platforms...
[2018-12-4 20:41:02] [Devolo] Initializing Devolo platform...
[2018-12-4 20:41:02] [Devolo] HBDevoloPlatform > Initializing (Version: 201702221607)
[2018-12-4 20:41:02] [Devolo] HBDevoloPlatform > Configuration:
{ platform: 'Devolo',
  name: 'Devolo',
  host: '192.168.178.40',
  email: 'xxx',
  password: 'xxx',
  uuid: 'xxx',
  gateway: 'xxx',
  passkey: 'xxx',
  heartrate: 3 }
[2018-12-4 20:41:02] [Devolo] HBDevoloPlatform > Searching for Devolo Central Unit.
Trying to connect to socket.
Websocket open
[2018-12-4 20:41:02] [Devolo] HBDevoloPlatform > Devolo API Version: 201707161504
[2018-12-4 20:41:02] [Devolo] HBDevoloCentralUnit > Initializing
[2018-12-4 20:41:02] [Devolo] HBDevoloPlatform > Central Unit found.
[2018-12-4 20:41:02] [Devolo] HBDevoloPlatform > SessionID: ID11125DB3PdkG91HpfML5MacBO6FiaL19HmpM21DEnd
[2018-12-4 20:41:07] [Devolo] HBDevoloShutterDevice > Initializing
[2018-12-4 20:41:07] [Devolo] HBDevoloShutterDevice > Initializing
[2018-12-4 20:41:07] [Devolo] HBDevoloMotionDevice > Initializing
[2018-12-4 20:41:07] [Devolo] HBDevoloDoorWindowDevice > Initializing
[2018-12-4 20:41:07] [Devolo] HBDevoloDoorWindowDevice > Initializing
[2018-12-4 20:41:07] [Devolo] HBDevoloSirenDevice > Initializing
[2018-12-4 20:41:07] [Devolo] HBDevoloSmokeDetectorDevice > Initializing
[2018-12-4 20:41:07] [Devolo] HBDevoloRelayDevice > Initializing
[2018-12-4 20:41:07] [Devolo] HBDevoloDoorWindowDevice > Initializing
[2018-12-4 20:41:07] [Devolo] HBDevoloSwitchMeterDevice > Initializing
[2018-12-4 20:41:07] [Devolo] HBDevoloSmokeDetectorDevice > Initializing
[2018-12-4 20:41:07] [Devolo] HBDevoloFloodDevice > Initializing
[2018-12-4 20:41:07] [Devolo] HBDevoloSmokeDetectorDevice > Initializing
[2018-12-4 20:41:07] [Devolo] HBDevoloDoorWindowDevice > Initializing
[2018-12-4 20:41:07] [Devolo] HBDevoloFloodDevice > Initializing
[2018-12-4 20:41:07] [Devolo] HBDevoloDoorWindowDevice > Initializing
[2018-12-4 20:41:07] [Devolo] HBDevoloDoorWindowDevice > Initializing
[2018-12-4 20:41:07] [Devolo] HBDevoloDoorWindowDevice > Initializing
[2018-12-4 20:41:07] [Devolo] HBDevoloDoorWindowDevice > Initializing
[2018-12-4 20:41:07] [Devolo] HBDevoloDoorWindowDevice > Initializing
[2018-12-4 20:41:07] [Devolo] HBDevoloThermostatValveDevice > Initializing
[2018-12-4 20:41:07] [Devolo] HBDevoloDoorWindowDevice > Initializing
[2018-12-4 20:41:07] [Devolo] HBDevoloDoorWindowDevice > Initializing
[2018-12-4 20:41:10] [Devolo] Initializing platform accessory 'Devolo Central Unit'...
[2018-12-4 20:41:10] [Devolo] Initializing platform accessory 'Rollladen Rechts'...

**Comment by nicoh88** [comment]
@kdietrich 

Kannst du es dir bitte mal anschauen?

Mit node v10.14.1 und v11.3.0 bekommt man folgende Fehlermeldung beim Starten von Homebridge:

```
[3.12.2018, 22:27:28] [Devolo] HBDevoloPlatform > Searching for Devolo Central Unit.
[3.12.2018, 22:27:28] [Devolo] HBDevoloPlatform > Could not get dhlp portal. Try again later.
Trying to connect to socket.
[3.12.2018, 22:27:28] [Devolo] HBDevoloPlatform > Could not get session. Try again later.
Websocket open
[3.12.2018, 22:27:28] [Devolo] HBDevoloPlatform > Devolo API Version: 201707161504
[3.12.2018, 22:27:28] [Devolo] HBDevoloCentralUnit > Initializing
[3.12.2018, 22:27:28] [Devolo] HBDevoloPlatform > Central Unit found.
[3.12.2018, 22:27:28] [Devolo] HBDevoloPlatform > SessionID: ID11060DB4GopML1GehOMNIlcI9PPapNPOKknOPMLEnd
/usr/local/lib/node_modules/homebridge-devolo/dist/index.js:65
throw err;
^

TypeError: Cannot read property 'length' of undefined
at /usr/local/lib/node_modules/homebridge-devolo/node_modules/node-devolo/dist/Devolo.js:141:39
at /usr/local/lib/node_modules/homebridge-devolo/node_modules/node-devolo/dist/DevoloApi.js:188:17
at IncomingMessage. (/usr/local/lib/node_modules/homebridge-devolo/node_modules/node-devolo/dist/DevoloApi.js:69:21)
at IncomingMessage.emit (events.js:187:15)
at endReadableNT (_stream_readable.js:1098:12)
at process.internalTickCallback (internal/process/next_tick.js:72:19)
```

BTW: Mit node v8.11.4 funktioniert es!

**Comment by kdietrich** [comment]
Gefixt in der neueste master: `npm install kdietrich/homebridge-devolo#master -g --unsafe-perm`
