### ISSUE TITLE
Fehler Inbetriebnahme Homebridge-Devolo

### ISSUE THREAD

**Issue by BaronT808** [kdietrich/homebridge-devolo#72]
Hi,

ich habe leider ein Problem wenn ich alles installiere und die Instanz starte. 
ich hatte erst den Fehler dass, das Homebridge-Plugin nicht in der Package.json unter Keyword steht. Dies habe ich gemacht.
Nun wirft mir der Debug folgende Fehler raus. 

`

2020-09-03 22:28:15.056  - info: host.raspberrypi instance system.adapter.ham.0 started with pid 23109
--
2020-09-03 22:28:15.907  - debug: ham.0 (23109) Redis Objects: Use Redis connection: 127.0.0.1:9001
2020-09-03 22:28:15.938  - debug: ham.0 (23109) Objects client ready ... initialize now
2020-09-03 22:28:15.942  - debug: ham.0 (23109) Objects create System PubSub Client
2020-09-03 22:28:15.943  - debug: ham.0 (23109) Objects create User PubSub Client
2020-09-03 22:28:15.944  - debug: ham.0 (23109) Objects client initialize lua scripts
2020-09-03 22:28:15.958  - debug: ham.0 (23109) Objects connected to redis: 127.0.0.1:9001
2020-09-03 22:28:15.964  - debug: ham.0 (23109) objectDB connected
2020-09-03 22:28:15.967  - debug: ham.0 (23109) Redis States: Use Redis connection: 127.0.0.1:9000
2020-09-03 22:28:15.975  - debug: ham.0 (23109) States create User PubSub Client
2020-09-03 22:28:15.978  - debug: ham.0 (23109) States create System PubSub Client
2020-09-03 22:28:15.988  - debug: ham.0 (23109) States connected to redis: 127.0.0.1:9000
2020-09-03 22:28:15.989  - debug: ham.0 (23109) statesDB connected
2020-09-03 22:28:16.138  - info: ham.0 (23109) starting. Version 1.1.2 in /opt/iobroker/node_modules/iobroker.ham, node: v12.18.3, js-controller: 3.1.6
2020-09-03 22:28:16.167  - info: ham.0 (23109) No additional Libraries to install ...
2020-09-03 22:28:17.569  - debug: ham.0 (23109) [2020-9-3 22:28:17] Loaded plugin: homebridge-devolo
2020-09-03 22:28:17.571  - debug: ham.0 (23109) [2020-9-3 22:28:17] Registering platform 'homebridge-devolo.Devolo'
2020-09-03 22:28:17.572  - debug: ham.0 (23109) [2020-9-3 22:28:17] ---
2020-09-03 22:28:17.586  - debug: ham.0 (23109) [2020-9-3 22:28:17] Loading 1 platforms...
2020-09-03 22:28:17.587  - debug: ham.0 (23109) [2020-9-3 22:28:17] [Devolo] Initializing Devolo platform...
2020-09-03 22:28:17.593  - debug: ham.0 (23109) [2020-9-3 22:28:17] [Devolo] HBDevoloPlatform > Searching for Devolo Central Unit.
2020-09-03 22:28:17.607  - debug: ham.0 (23109) [2020-9-3 22:28:17] Loading 0 accessories...
2020-09-03 22:28:17.689  - debug: ham.0 (23109) Trying to connect to socket.
2020-09-03 22:28:17.757  - debug: ham.0 (23109) Websocket open
2020-09-03 22:28:17.761  - debug: ham.0 (23109) [2020-9-3 22:28:17] [Devolo] HBDevoloPlatform > Central Unit found.
2020-09-03 22:28:18.823  - debug:  ham.0 (23109) Device > %s < is not supported (yet) or devolo has  something changed. Open an issue on github and ask for adding it.
> Model: %s
> ProductID: %s
> ProductTypeID: %s
> Sensors: %s
2020-09-03 22:28:18.825  - debug:  ham.0 (23109) Device > %s < is not supported (yet) or devolo has  something changed. Open an issue on github and ask for adding it.
> Model: %s
> ProductID: %s
> ProductTypeID: %s
> Sensors: %s
2020-09-03 22:28:18.826  - debug:  ham.0 (23109) Device > %s < is not supported (yet) or devolo has  something changed. Open an issue on github and ask for adding it.
> Model: %s
> ProductID: %s
> ProductTypeID: %s
> Sensors: %s
2020-09-03 22:28:18.827  - debug:  ham.0 (23109) Device > %s < is not supported (yet) or devolo has  something changed. Open an issue on github and ask for adding it.
> Model: %s
> ProductID: %s
> ProductTypeID: %s
> Sensors: %s
2020-09-03 22:28:18.829  - debug:  ham.0 (23109) Device > %s < is not supported (yet) or devolo has  something changed. Open an issue on github and ask for adding it.
> Model: %s
> ProductID: %s
> ProductTypeID: %s
> Sensors: %s
2020-09-03 22:28:18.830  - debug:  ham.0 (23109) Device > %s < is not supported (yet) or devolo has  something changed. Open an issue on github and ask for adding it.
> Model: %s
> ProductID: %s
> ProductTypeID: %s
> Sensors: %s
2020-09-03 22:28:19.406  - error: ham.0 (23109) uncaught exception: Cannot read property 'length' of undefined
2020-09-03 22:28:19.408  - error: ham.0 (23109) TypeError: Cannot read property 'length' of undefined
at /opt/iobroker/node_modules/homebridge-devolo/node_modules/node-devolo/dist/Devolo.js:363:47
at /opt/iobroker/node_modules/homebridge-devolo/node_modules/node-devolo/dist/DevoloApi.js:185:17
at IncomingMessage. (/opt/iobroker/node_modules/homebridge-devolo/node_modules/node-devolo/dist/DevoloApi.js:69:21)
at IncomingMessage.emit (events.js:327:22)
at endReadableNT (_stream_readable.js:1220:12)
at processTicksAndRejections (internal/process/task_queues.js:84:21)
2020-09-03 22:28:19.409  - info: ham.0 (23109) cleaned everything up...
2020-09-03 22:28:19.417  - warn: ham.0 (23109) Exception: TypeError: Cannot read property 'length' of undefined
2020-09-03 22:28:19.429  - info: ham.0 (23109) terminating
2020-09-03 22:28:19.431  - info: ham.0 (23109) Terminated (NO_ERROR): Without reason
2020-09-03 22:28:20.124  - error: host.raspberrypi Caught by controller[0]: [2020-9-3 22:28:17] ====================
2020-09-03 22:28:20.124  - error: host.raspberrypi Caught by controller[1]: [2020-9-3 22:28:17] ERROR LOADING PLUGIN homebridge-plugin-wrapper:
2020-09-03 22:28:20.125  - error:  host.raspberrypi Caught by controller[1]: [2020-9-3 22:28:17] Error:  Plugin /opt/iobroker/node_modules/homebridge-plugin-wrapper does not  contain the 'homebridge' package in 'engines'.
2020-09-03 22:28:20.125  - error:  host.raspberrypi Caught by controller[1]:     at Plugin.load  (/opt/iobroker/node_modules/homebridge-plugin-wrapper/homebridge/plugin.js:49:11)
2020-09-03 22:28:20.125  - error: host.raspberrypi Caught by controller[1]:     at Server. (/opt/iobroker/node_modules/homebridge-plugin-wrapper/homebridge/server.js:153:14)
2020-09-03 22:28:20.125  - error: host.raspberrypi Caught by controller[1]:     at Array.forEach ()
2020-09-03 22:28:20.126  - error:  host.raspberrypi Caught by controller[1]:     at Server._loadPlugins  (/opt/iobroker/node_modules/homebridge-plugin-wrapper/homebridge/server.js:145:22)
2020-09-03 22:28:20.126  - error:  host.raspberrypi Caught by controller[1]:     at new Server  (/opt/iobroker/node_modules/homebridge-plugin-wrapper/homebridge/server.js:57:24)
2020-09-03 22:28:20.126  - error:  host.raspberrypi Caught by controller[1]:     at HomebridgeWrapper.init  (/opt/iobroker/node_modules/homebridge-plugin-wrapper/index.js:221:19)
2020-09-03 22:28:20.127  - error:  host.raspberrypi Caught by controller[1]:     at Object.start  (/opt/iobroker/node_modules/iobroker.ham/lib/wrapper-handler.js:111:23)
2020-09-03 22:28:20.127  - error: host.raspberrypi Caught by controller[1]:     at /opt/iobroker/node_modules/iobroker.ham/main.js:276:39
2020-09-03 22:28:20.127  - error: host.raspberrypi Caught by controller[1]:     at /opt/iobroker/node_modules/iobroker.ham/main.js:177:27
2020-09-03 22:28:20.127  - error: host.raspberrypi Caught by controller[1]:     at /opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:4008:33
2020-09-03 22:28:20.128  - error: host.raspberrypi Caught by controller[1]: [2020-9-3 22:28:17] ====================
2020-09-03 22:28:20.128  - info: host.raspberrypi instance system.adapter.ham.0 terminated with code 0 (NO_ERROR)
2020-09-03 22:28:20.128  - info: host.raspberrypi Restart adapter system.adapter.ham.0 because enabled
 `

Meine Konfigdatei:

{
  "accessories": [],
  "platforms": [
    {
      "platform": "Devolo",
      "name": "Devolo",
      "host": "192.168.002.103",
      "email": "xxxxx@xx.com",
      "password": "xxxxxxx",
      "uuid": "4xxxxx3F-8FC0-xxE3-A804-xxxxxxxxxxxxxxxxB15",
      "gateway": "xxxxxxxxxxxxxxxxxxxxxx",
      "passkey": "xxxxxxxxxxxxxxxxxxxxx9"
    }
  ]
}

Die Werte habe ich wie beschrieben mit meinen Daten ausgefüllt.

Kannst du mir bitte weiterhelfen. Im iobroker Forum konnte mir keiner helfen.

Vielen Dank für deine Zeit

Mfg Tobi

**Comment by gwi2014** [comment]
Hi, das Log sieht komisch aus. Überall wo %s steht, sollte eigentlich ein Wert stehen. Kannst du sagen, wie du was startest und welche node.js Version du verwendest?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BaronT808** [comment]
Ich habe gedacht das wäre zwave geräte in meiner Devolo Zentrale die von anderen Herstellern sind und ggf. nicht unterstützt werden.
Ich starte die Instanz ham im iobroker. 
Meine Note Version ist 12.x falls du die genaue brauchst kann ich sie dir morgen sagen.

Hier noch der Link von iobroker Forum. Damit ihr alle info dazu habt.:
https://forum.iobroker.net/topic/36457/ham-homebridge-devolo-fehler/5

Mfg Tobi

**Comment by BaronT808** [comment]
Hallo zusammen,

Hat vllt. noch einer eine Idee was ich noch versuchen kann. Ich habe mittlerweile  mal alles neu installiert. Dort habe ich genau das selbe Problem.

Mfg Tobi

**Comment by MikeyRZW** [comment]
Hi,
ich würde mal in der Config
"host": "192.168.2.103", versuchen, also ohne die zwei führenden Nullen

**Comment by BaronT808** [comment]
Das probiere ich morgen mal aus. Ich gebe dann Rückmeldung. Vielen Dank


Ich denke das ich mir einen zweiten Raspberry zulegen werde wo ich Home Assistant drauf spiele. Dieser unterstützt Devolo. Dann kann ich den Hass in den Iobroker einbinden und ich habe mein Devolo im Iobroker. Ist zwar etwas kompliziert gelöst aber ich denke von der Zeit und der Kosten das beste was ich in dieser Situation noch machen kann...

Mfg Tobi
