### ISSUE TITLE
Crash bei zu viel Last auf dem Homebridge-Server

### ISSUE THREAD

**Issue by nicoh88** [kdietrich/homebridge-devolo#9]
Hi Kevin,

wenn der Homebridge-Server gerade ausgelastet ist, kann das Devolo-Plugin offensichtlich nicht schnell genug die eingehenden Nachrichten verarbeiten und stürzt ab. Bitte beheben. 👍 

```homebridge[31519]: [2017-04-24 11:10:09] [Devolo] HBDevoloSwitchMeterDevice > CurrentConsumption 43.3 > 43.8
homebridge[31519]: [2017-04-24 11:10:18] [Devolo] HBDevoloSwitchMeterDevice > CurrentConsumption 43.8 > 44.4
homebridge[31519]: [2017-04-24 11:10:42] [Devolo] SyntaxError: Unexpected end of JSON input
homebridge[31519]: at Object.parse (native)
homebridge[31519]: at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-devolo/node_modules/node-devolo/dist/DevoloApi.js:63:36)
homebridge[31519]: at emitNone (events.js:91:20)
homebridge[31519]: at IncomingMessage.emit (events.js:185:7)
homebridge[31519]: at endReadableNT (_stream_readable.js:975:12)
homebridge[31519]: at _combinedTickCallback (internal/process/next_tick.js:74:11)
homebridge[31519]: at process._tickCallback (internal/process/next_tick.js:98:9)
homebridge[31519]: /usr/local/lib/node_modules/homebridge-devolo/node_modules/node-devolo/dist/DevoloApi.js:182
homebridge[31519]: if (res.error) {
homebridge[31519]: ^
homebridge[31519]: TypeError: Cannot read property 'error' of undefined
homebridge[31519]: at /usr/local/lib/node_modules/homebridge-devolo/node_modules/node-devolo/dist/DevoloApi.js:182:20
homebridge[31519]: at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-devolo/node_modules/node-devolo/dist/DevoloApi.js:71:17)
homebridge[31519]: at emitNone (events.js:86:13)
homebridge[31519]: at IncomingMessage.emit (events.js:185:7)
homebridge[31519]: at IncomingMessage.<anonymous> (_http_client.js:277:11)
homebridge[31519]: at emitNone (events.js:91:20)
homebridge[31519]: at IncomingMessage.emit (events.js:185:7)
homebridge[31519]: at endReadableNT (_stream_readable.js:975:12)
homebridge[31519]: at _combinedTickCallback (internal/process/next_tick.js:74:11)
homebridge[31519]: at process._tickCallback (internal/process/next_tick.js:98:9)
systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE
systemd[1]: Unit homebridge.service entered failed state.
systemd[1]: homebridge.service holdoff time over, scheduling restart.```

**Comment by kdietrich** [comment]
Sollte nun nicht mehr vorkommen!
